-- AlterTable
ALTER TABLE `forum` ADD COLUMN `dislikeCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `likeCount` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `report` ADD COLUMN `status` ENUM('PENDING', 'RESOLVED', 'REJECTED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `resource` ADD COLUMN `isPublished` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `user` ADD COLUMN `avatarUrl` VARCHAR(191) NULL,
    ADD COLUMN `status` ENUM('ACTIVE', 'SUSPENDED', 'BANNED') NOT NULL DEFAULT 'ACTIVE';
